CREATE TABLE transactions (
    actual_worth            NUMERIC,
    area_id                 INTEGER,
    area_name               VARCHAR(150),
    building_name           VARCHAR(200),
    has_parking              INTEGER,
    instance_date             DATE,
    master_project             VARCHAR(200),
    meter_sale_price           NUMERIC,
    nearest_landmark            VARCHAR(200),
    nearest_mall                 VARCHAR(200),
    nearest_metro                 VARCHAR(200),
    no_of_parties_role_1           NUMERIC,
    no_of_parties_role_2           NUMERIC,
    no_of_parties_role_3           NUMERIC,
    procedure_area                  NUMERIC,
    procedure_id                     INTEGER,
    procedure_name                    VARCHAR(200),
    project_name                       VARCHAR(200),
    project_number                      NUMERIC,
    property_sub_type                    VARCHAR(150),
    property_sub_type_id                  NUMERIC,
    property_type                          VARCHAR(50),
    property_type_id                        INTEGER,
    property_usage                           VARCHAR(50),
    reg_type                                  VARCHAR(100),
    reg_type_id                                INTEGER,
    rooms                                       VARCHAR(20),
    transaction_id                               VARCHAR(50),
    trans_group                                   VARCHAR(50),
    trans_group_id                                 INTEGER,
    year                                             INTEGER,
    month                                             INTEGER,
    actual_worth_capped                                NUMERIC
);
COPY transactions FROM 'C:\Dubai Real Estate Market Intelligence Platform\data\cleaned\real_estate_transactions.csv' 
DELIMITER ',' CSV HEADER;